[exercises](intro.ipynb)

In [1]:
import numpy as np

In [2]:
np.arange(6)

array([0, 1, 2, 3, 4, 5])

In [3]:
np.arange(0, 0.6, 0.1), np.arange(6) * 0.1  # two possibilities

(array([ 0. ,  0.1,  0.2,  0.3,  0.4,  0.5]),
 array([ 0. ,  0.1,  0.2,  0.3,  0.4,  0.5]))

In [4]:
np.arange(0.5, 1.1, 0.1), "<-- wrong result!"

(array([ 0.5,  0.6,  0.7,  0.8,  0.9,  1. ,  1.1]), '<-- wrong result!')

In [5]:
np.arange(5, 11) * 0.1, "<-- that's right!"

(array([ 0.5,  0.6,  0.7,  0.8,  0.9,  1. ]), "<-- that's right!")

In [6]:
np.linspace(0, 6, 7)

array([ 0.,  1.,  2.,  3.,  4.,  5.,  6.])

In [7]:
np.linspace(0, 6, 6, endpoint=False), np.linspace(0, 5, 6)  # two possibilities

(array([ 0.,  1.,  2.,  3.,  4.,  5.]), array([ 0.,  1.,  2.,  3.,  4.,  5.]))

In [8]:
np.linspace(0, 0.6, 6, endpoint=False), np.linspace(0, 0.5, 6)  # again two possibilities

(array([ 0. ,  0.1,  0.2,  0.3,  0.4,  0.5]),
 array([ 0. ,  0.1,  0.2,  0.3,  0.4,  0.5]))

In [9]:
np.linspace(0.5, 1.1, 6, endpoint=False), np.linspace(0.5, 1, 6)  # and again ...

(array([ 0.5,  0.6,  0.7,  0.8,  0.9,  1. ]),
 array([ 0.5,  0.6,  0.7,  0.8,  0.9,  1. ]))

If the number of elements is known and the step size should be obtained automatically $\Rightarrow$ `np.linspace()`  
If the step size is known an if it's an integer and the number of elements should be obtained automatically $\Rightarrow$ `np.arange()`

If the step size is not an integer:

* If the step size is a fraction of integers, you can use `np.arange()` with integers and divide the result accordingly.

* If that's not feasible, calculate the expected number of elements beforehand and use `np.linspace()`

In [10]:
dur, amp, freq, fs = 1, 0.3, 500, 44100
t = np.arange(np.ceil(dur * fs)) / fs
y = amp * np.sin(2 * np.pi * freq * t)

alternative (but inferior) methods to get $t$:

In [11]:
t = np.arange(0, dur, 1/fs)  # implicit rounding of dur!
t = np.arange(0, np.round(dur), 1/fs)  # still problematic: arange with floats
# wrong if dur isn't an integer multiple of 1/fs:
t = np.linspace(0, dur, np.round(dur * fs), endpoint=False)

Length of `y` must be *exactly* 44100 (using a half-open interval for $t$), not 44101 (which would be longer than 1 second).

Plotting: 2 ways to zoom (there are probably more): draw a rectangle, drag with the right mouse button in pan/zoom mode.

Clicks? Because of discontinuities (also in the derivatives) $\Rightarrow$ Fade in/out!

In [12]:
import numpy as np

def mysine(frequency, amplitude, duration, samplerate):
    """Generate sine tone with given frequency/amplitude/duration."""
    t = np.arange(np.ceil(duration * samplerate)) / samplerate
    return amplitude * np.sin(2 * np.pi * frequency * t)

In [13]:
import matplotlib.pyplot as plt

def myplot(data, samplerate):
    """Create a simple plot."""
    t = np.arange(len(data)) / samplerate
    plt.plot(t, data)
    plt.xlabel("Time / Seconds")

In [14]:
import soundfile as sf

dur, amp, fs = 1, 0.3, 44100
frequencies = 400, 500, 600

for freq in frequencies:
    sig = mysine(freq, amp, dur, fs)
    sf.write("sine_{}hz.wav".format(freq), sig, fs)

In [15]:
from scipy import signal

f0, f1 = 100, 5000  # Hz
fs = 44100
amp = 0.3
dur = 2

t = np.arange(np.ceil(dur * fs)) / fs

for method in 'linear', 'log':
    sweep = amp * signal.chirp(t, f0, dur, f1, method)
    sf.write('sweep_{}.wav'.format(method), sweep, fs)

superposition: TODO

<http://en.wikipedia.org/wiki/Beat_(acoustics)>

two-channel sine signals: TODO

The first column should be the left channel!

Difference between `len()`, `a.shape` and `a.size`: see documentation!

In [16]:
import numpy as np
import sounddevice as sd

dur, amp, fs = 1, 0.3, 44100
frequencies = 500, 1000, 2000  # Hz
delays = 0.6, 0.4, 0.2, 0, -0.2, -0.4, -0.6  # ms

t = np.arange(np.ceil(dur * fs)) / fs

for f in frequencies:
    for delay in delays:
        times = np.column_stack((t, t - delay/1000))
        sig = amp * np.sin(2 * np.pi * f * times)
        sd.play(sig, blocking=True)

This is supposed to illustrate [Lord Rayleigh's Duplex Theory](http://en.wikipedia.org/wiki/Interaural_time_difference#Duplex_theory) (at least the part about time differences).

<p xmlns:dct="http://purl.org/dc/terms/">
  <a rel="license"
     href="http://creativecommons.org/publicdomain/zero/1.0/">
    <img src="http://i.creativecommons.org/p/zero/1.0/88x31.png" style="border-style: none;" alt="CC0" />
  </a>
  <br />
  To the extent possible under law,
  <span rel="dct:publisher" resource="[_:publisher]">the person who associated CC0</span>
  with this work has waived all copyright and related or neighboring
  rights to this work.
</p>